#!/usr/bin/python3
import sys
import time
import math

''' this is docuement 
 
'''


def factorize(n):
    if n % 2 == 0:
        return (2, n // 2)
    for i in range(3, math.isqrt(n) + 1, 2):
        if n % i == 0:
            return (i, n // i)
    return None

def factorize_file(file_path):

    numbers = []
    file = open(file_path, 'r')
    numbers = [int(line.strip()) for line in file]
    for number in numbers:
        factorization = factorize(number)
        if factorization is not None:
            p, q = factorization
            print(f"{number}={q}*{p}")


if __name__ == "__main__":

    if len(sys.argv) < 2:
        print("Usage: ./factors <file>")
    else:
        factorize_file(sys.argv[1])
