#!/usr/bin/env python3
import sys
import time
import math


def factorize(n):

    for i in range(2, math.isqrt(n) + 1):
        if n % i == 0:
            return (i, n//i)
    return None


def factorize_file(file_path):

    start_time = time.time()

    numbers = []
    try:
        with open(file_path, 'r') as file:
            numbers = [int(line.strip()) for line in file]
    except FileNotFoundError:
        print(f"File '{file_path}' not found.")
        return
    except ValueError:
        print(f"Invalid input in file '{file_path}'.")
        return
    for number in numbers:
        if time.time() - start_time > 5:
            break
        factorization = factorize(number)
        if factorization is not None:
            p, q = factorization
            print(f"{number}={q}*{p}")


if __name__ == "__main__":

    if len(sys.argv) < 2:
        print("Usage: ./factors <file>")
    else:
        factorize_file(sys.argv[1])
